name: CI

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-ngrok:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download and Run Batch Script
        run: |
          Invoke-WebRequest -Uri 'https://gist.githubusercontent.com/Leopold192/31f9934d0a60f3f8ad8ded49ef09f87a/raw/14d85656228bfc3ec9862f549d22285c1b51e38f/run-ngrok.bat' -OutFile run-ngrok.bat
          echo Running batch script...
          .\run-ngrok.bat ${{ secrets.NGROK_AUTH_TOKEN }}
        shell: pwsh
